name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Quick Docker Cleanup
      run: |
        docker compose down
        docker system prune -af --volumes --filter "until=24h"
        
    - name: Create env files
      run: |
        # API Environment Variables
        echo "DATABASE_URL=postgresql://admin:admin@postgres:5432/vorex_db?schema=public" > apps/api/.env
        echo "JWT_SECRET=8f4c9d6a2e7b1f5n8q3w9p4m7k2j5h8g1t6y3r9c4v7b2n5x8z1l6s3d9g4h7j" >> apps/api/.env
        echo "JWT_EXPIRES_IN=7d" >> apps/api/.env
        echo "PORT=3000" >> apps/api/.env
        echo "NODE_ENV=production" >> apps/api/.env
        echo "ALLOWED_ORIGINS=http://40.67.192.108,http://40.67.192.108:80" >> apps/api/.env
        echo "CORS_ENABLED=true" >> apps/api/.env
        
        # Web Environment Variables
        echo "VITE_API_URL=http://40.67.192.108/api" > apps/web/.env
        echo "VITE_APP_NAME=Vorex" >> apps/web/.env
        
    - name: Deploy with Docker Compose
      run: |
        docker compose up -d --build --force-recreate --remove-orphans
        docker ps 