name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Cleanup Docker
      run: |
        # Stop all containers
        docker compose down
        
        # Remove all buildx builders
        docker buildx rm -f $(docker buildx ls -q) || true
        
        # Remove all unused volumes (except postgres_data)
        docker volume ls -q | grep -v postgres_data | xargs -r docker volume rm || true
        
        # Prune system
        docker system prune -af --volumes
        
        # Create new builder
        docker buildx create --use --name fresh-builder
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Create env files
      run: |
        # API Environment Variables
        echo "DATABASE_URL=postgresql://admin:admin@postgres:5432/vorex_db?schema=public" > apps/api/.env
        echo "JWT_SECRET=8f4c9d6a2e7b1f5n8q3w9p4m7k2j5h8g1t6y3r9c4v7b2n5x8z1l6s3d9g4h7j" >> apps/api/.env
        echo "JWT_EXPIRES_IN=7d" >> apps/api/.env
        echo "PORT=3000" >> apps/api/.env
        echo "NODE_ENV=production" >> apps/api/.env
        echo "ALLOWED_ORIGINS=http://40.67.192.108,http://40.67.192.108:80" >> apps/api/.env
        echo "CORS_ENABLED=true" >> apps/api/.env
        
        # Web Environment Variables
        echo "VITE_API_URL=http://40.67.192.108/api" > apps/web/.env
        echo "VITE_APP_NAME=Vorex" >> apps/web/.env
        
    - name: Deploy with Docker Compose
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: |
        # Build with no-cache to ensure fresh builds
        docker compose build --no-cache --parallel
        
        # Start containers
        docker compose up -d
        
        # Wait for containers
        sleep 30
        
        # Cleanup after successful deployment
        docker system prune -af --filter "until=24h"
        
        # Check container status
        docker ps
        docker compose logs 