name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Create env files
      run: |
        # API Environment Variables
        echo "DATABASE_URL=postgresql://admin:admin@postgres:5432/vorex_db?schema=public" > apps/api/.env
        echo "JWT_SECRET=your-secret-key" >> apps/api/.env
        echo "JWT_EXPIRES_IN=7d" >> apps/api/.env
        echo "PORT=3000" >> apps/api/.env
        
        # Web Environment Variables
        echo "VITE_API_URL=http://128.251.128.84:3000" > apps/web/.env
        
    - name: Deploy with Docker Compose
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: |
        # Stop existing containers
        docker compose down || true
        
        # Remove unused images and volumes
        docker system prune -af
        
        # Build and start containers
        docker compose build --parallel
        docker compose up -d
        
        # Wait for containers to start
        sleep 30
        
        # Check container status
        docker ps
        docker compose logs 