name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Create env files
      run: |
        # API Environment Variables
        echo "DATABASE_URL=postgresql://admin:admin@postgres:5432/vorex_db?schema=public" > apps/api/.env
        echo "JWT_SECRET=8f4c9d6a2e7b1f5n8q3w9p4m7k2j5h8g1t6y3r9c4v7b2n5x8z1l6s3d9g4h7j" >> apps/api/.env
        echo "JWT_EXPIRES_IN=7d" >> apps/api/.env
        echo "PORT=3000" >> apps/api/.env
        echo "NODE_ENV=production" >> apps/api/.env
        echo "ALLOWED_ORIGINS=http://128.251.128.84,http://128.251.128.84:80" >> apps/api/.env
        echo "CORS_ENABLED=true" >> apps/api/.env
        
        # Web Environment Variables
        echo "VITE_API_URL=http://128.251.128.84/api" > apps/web/.env
        echo "VITE_APP_NAME=Vorex" >> apps/web/.env
        
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
        
    - name: Deploy with Docker Compose
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: |
        # Stop existing containers
        docker compose down || true
        
        # Remove unused images and volumes
        docker system prune -af
        
        # Build and start containers with BuildKit
        docker compose build --parallel
        docker compose up -d
        
        # Wait for containers to start
        sleep 30
        
        # Check container status
        docker ps
        docker compose logs 